blank_issues_enabled: false
contact_links:
  - name: Original SuccessStory Plugin Issues
    url: https://github.com/Lacro59/playnite-successstory-plugin/issues
    about: Please check if your issue exists in the original repository first
    
name: 👋 Want to contribute to playnite-successstory-plugin fork?
description: |
  Before submitting, please check if your issue is related to this fork's specific features:
  - Steam Emulator achievements
  - Xbox 360 achievements
  - ShadPS4 achievements
  
  For general plugin issues, please check Lacro59's repository first.
