blank_issues_enabled: false
contact_links:
  - name: Original SuccessStory Plugin Issues
    url: https://github.com/Lacro59/playnite-successstory-plugin/issues
    about: Please check if your issue exists in the original repository first
