name: "👋 Want to contribute to playnite-successstory-plugin fork?"
description: |
  Before submitting, please check if your issue is related to this fork's specific features:
  - Steam Emulator achievements
  - Xbox 360 achievements
  - ShadPS4 achievements
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to contribute to this fork!
  - type: textarea
    attributes:
      label: "Thanks for helping"
