name: "👋 Want to contribute to playnite-successstory-plugin fork?"
description: |
  Before submitting, check if your issue relates to the specific features of this fork:
  - Steam Emulator achievements
  - Xbox 360 achievements
  - ShadPS4 achievements

  For general issues, check Lacro59's repository first.
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to contribute to this fork!
  - type: textarea
    attributes:
      label: "Thanks for helping"
